=== GII/broccoli/broccoli-api/src/main/resources/com/hi3project/broccoli/ontology/bsdlSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!--

Copyright (C) 2015 Mytech Ingenieria Aplicada <http://www.mytechia.com>
Copyright (C) 2015 Alejandro Paz <alejandropl@lagostelle.com>

This file is part of Broccoli.

Broccoli is free software: you can redistribute it and/or modify it under the
terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.

Broccoli is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
details.

You should have received a copy of the GNU Affero General Public License
along with Broccoli. If not, see <http://www.gnu.org/licenses/>.

-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified">
    
    
    <!-- ************************************************************ simple & reusable elements ******************************************************************** -->
    
    <xs:element name="literal">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="string"/>
                <xs:enumeration value="integar"/>
                <xs:enumeration value="decimal"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element> 
    
    <xs:element name="multiplicity">
        <xs:complexType>
            <xs:attribute name="min" type="xs:string"/>
            <xs:attribute name="max" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="import">
        <xs:complexType>
            <xs:attribute name="prefix" type="xs:string" use="required"/>
            <xs:attribute name="to" type="xs:anyURI" use="required"/>            
            
            <xs:attribute name="dialect" type="xs:anyURI"/>
            <xs:attribute name="lang" type="xs:anyURI"/>
        </xs:complexType>
    </xs:element>
    

    <!-- ************************************************************ complex elements: concept ********************************************************************* -->


        <xs:complexType mixed="true" name="property">

            <xs:sequence>
                <xs:element ref="concept" minOccurs="0"/>
                <xs:element ref="multiplicity" minOccurs="0" maxOccurs="1"/>
                <xs:element name="property" type="property" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>

            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="URI" type="xs:anyURI"/>

        </xs:complexType>

    <xs:element name="concept">
        <xs:complexType>
        
            <xs:sequence>
                <xs:element ref="import" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="subconceptOf" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:choice>
                            <xs:element name="URI" type="xs:anyURI"/>
                            <xs:element ref="concept" />
                        </xs:choice>
                    </xs:complexType>
                </xs:element>
                <xs:element name="property" type="property" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            
            <xs:attribute name="URI" type="xs:anyURI" use="required"/>
            <xs:attribute name="subconceptOf" type="xs:anyURI"/>
            
            <xs:attribute name="ontology" type="xs:anyURI"/>
            
            <xs:attribute name="ontologyLanguage" type="xs:anyURI"/>
            <xs:attribute name="naturalLanguage" type="xs:string"/>
            
        </xs:complexType>
    </xs:element>
    

    
    
    <!-- ************************************************************ complex elements: instance ******************************************************************** -->
    
    <xs:element name="instance">        
        <xs:complexType>
            
            <xs:sequence>
                <xs:element ref="import" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="with" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            
            <xs:attribute name="of" type="xs:string" use="required"/>
            <xs:attribute name="URI" type="xs:anyURI"/>  
            
            <xs:attribute name="ontology" type="xs:anyURI"/>
            
        </xs:complexType>                    
    </xs:element> 
    
    <xs:element name="with" >
        <xs:complexType mixed="true">     
        
            <xs:choice minOccurs="0">       
                <xs:element name="URI" type="xs:anyURI"/>
                <xs:element ref="concept" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="instance" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="literal" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="with" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            
            <xs:attribute name="property" type="xs:string" use="required"/>
            <xs:attribute name="valueURI" type="xs:string"/>
            <xs:attribute name="value" type="xs:string"/>
            <xs:attribute name="ofURI" type="xs:anyURI"/>
            
            <xs:attribute name="ontology" type="xs:anyURI"/>
            
        </xs:complexType>        
    </xs:element> 
    
    
    <!-- ************************************************************ complex elements: ontology ********************************************************************* -->
    
    <xs:element name="ontology">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="concept" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="instance" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            
            <xs:attribute name="URI" type="xs:anyURI" use="required"/>
        
            <xs:attribute name="ontologyLanguage" type="xs:anyURI"/>
            <xs:attribute name="naturalLanguage" type="xs:string"/>
            <xs:attribute name="versionNumber" type="xs:string"/>                        
        </xs:complexType>
                
    </xs:element>

</xs:schema>

=== GII/broccoli/broccoli-api/src/main/resources/com/hi3project/broccoli/ontology/bsdmOntology.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--

Copyright (C) 2015 Mytech Ingenieria Aplicada <http://www.mytechia.com>
Copyright (C) 2015 Alejandro Paz <alejandropl@lagostelle.com>

This file is part of Broccoli.

Broccoli is free software: you can redistribute it and/or modify it under the
terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.

Broccoli is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
details.

You should have received a copy of the GNU Affero General Public License
along with Broccoli. If not, see <http://www.gnu.org/licenses/>.

-->


<ontology URI="http://hi3project.com/broccoli/bsdm#ontology"
          ontologyLanguage="http://hi3project.com/broccoli/bsdl#ontology"
          versionNumber="0.9.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="bsdlSchema.xsd">


    <!-- Service -->

    <concept URI="http://hi3project.com/broccoli/bsdm#serviceDescription"
             ontology="http://hi3project.com/broccoli/bsdm#ontology">

        <property name="grounding" URI="http://hi3project.com/broccoli/bsdm#serviceGrounding">
            <multiplicity min="0" max="*"/>
        </property>

        <property name="profile" URI="http://hi3project.com/broccoli/bsdm#serviceProfile">
            <multiplicity min="1" max="1"/>
        </property>

        <property name="implementation" URI="http://hi3project.com/broccoli/bsdm#serviceImplementation">
            <multiplicity min="0" max="*"/>
        </property>

        <property name="name" URI="http://hi3project.com/broccoli/bsdl#literal">
            <multiplicity min="1" max="1"/>
        </property>

    </concept>


    <!-- Profile -->

    <concept URI="http://hi3project.com/broccoli/bsdm#serviceProfile"
             ontology="http://hi3project.com/broccoli/bsdm#ontology">

        <property name="serviceType" URI="http://gii.udc.es/semanticServices#bsdm/profile/serviceType">
            <multiplicity min="0" max="1"/>
        </property>

        <property name="nonFunctionalProperty" URI="http://hi3project.com/broccoli/bsdm/profile#nonFunctionalProperty">
            <multiplicity min="0" max="*"/>
        </property>

        <property name="advertisedFunctionality"
                  URI="http://hi3project.com/broccoli/bsdm/profile#advertisedFunctionality">
            <multiplicity min="1" max="*"/>
        </property>

        <property name="advertisedSubscription"
                  URI="http://hi3project.com/broccoli/bsdm/profile#advertisedSubscription">
            <multiplicity min="1" max="*"/>
        </property>

        <property name="name" URI="http://hi3project.com/broccoli/bsdl#literal">
            <multiplicity min="1" max="1"/>
        </property>

        <property name="version" URI="http://hi3project.com/broccoli/bsdl#literal">
            <multiplicity min="1" max="1"/>
        </property>

    </concept>


    <concept URI="http://gii.udc.es/semanticServices#bsdm/profile/serviceType"
             ontology="http://hi3project.com/broccoli/bsdm#ontology">

        <property name="identifier" URI="http://hi3project.com/broccoli/bsdl#semanticIdentifier">
            <multiplicity min="1" max="1"/>
        </property>

    </concept>


    <concept URI="http://hi3project.com/broccoli/bsdm/profile#functionality"
             ontology="http://hi3project.com/broccoli/bsdm#ontology">

        <property name="functionalityCategory" URI="http://hi3project.com/broccoli/bsdm/profile#functionalityCategory">
            <multiplicity min="0" max="1"/>
        </property>

        <property name="input" URI="http://hi3project.com/broccoli/bsdm/profile#input">
            <multiplicity min="0" max="*"/>
        </property>

        <property name="output" URI="http://hi3project.com/broccoli/bsdm/profile#output">
            <multiplicity min="0" max="*"/>
        </property>

        <property name="effect" URI="http://hi3project.com/broccoli/bsdm/profile#effect">
            <multiplicity min="0" max="*"/>
        </property>

        <property name="nonFunctionalProperty" URI="http://hi3project.com/broccoli/bsdm/profile#nonFunctionalProperty">
            <multiplicity min="0" max="*"/>
        </property>

    </concept>

    <concept URI="http://hi3project.com/broccoli/bsdm/profile#serviceFunctionality"
             ontology="http://hi3project.com/broccoli/bsdm#ontology"
             subconceptOf="http://hi3project.com/broccoli/bsdm/profile#functionality">

        <property name="functionalityGrounding"
                  URI="http://hi3project.com/broccoli/bsdm/grounding#functionalityGrounding">
            <multiplicity min="0" max="*"/>
        </property>

        <property name="name" URI="http://hi3project.com/broccoli/bsdl#literal">
            <multiplicity min="1" max="1"/>
        </property>

    </concept>

    <concept URI="http://hi3project.com/broccoli/bsdm/profile#advertisedFunctionality"
             ontology="http://hi3project.com/broccoli/bsdm#ontology"
             subconceptOf="http://hi3project.com/broccoli/bsdm/profile#serviceFunctionality"/>

    <concept URI="http://hi3project.com/broccoli/bsdm/profile#advertisedSubscription"
             ontology="http://hi3project.com/broccoli/bsdm#ontology"
             subconceptOf="http://hi3project.com/broccoli/bsdm/profile#serviceFunctionality"/>


    <concept URI="http://hi3project.com/broccoli/bsdm/profile#condition"
             ontology="http://hi3project.com/broccoli/bsdm#ontology">

        <property name="type">
            <multiplicity min="0" max="1"/>
        </property>

    </concept>

    <concept URI="http://hi3project.com/broccoli/bsdm/profile#effect"
             ontology="http://hi3project.com/broccoli/bsdm#ontology">

        <property name="type">
            <multiplicity min="0" max="1"/>
        </property>

    </concept>

    <concept URI="http://hi3project.com/broccoli/bsdm/profile#functionalityCategory"
             ontology="http://hi3project.com/broccoli/bsdm#ontology">

        <property name="type" URI="http://hi3project.com/broccoli/bsdl#semanticIdentifier">
            <multiplicity min="0" max="1"/>
        </property>

    </concept>

    <concept URI="http://hi3project.com/broccoli/bsdm/profile#input"
             ontology="http://hi3project.com/broccoli/bsdm#ontology"
             subconceptOf="http://hi3project.com/broccoli/bsdm/profile#parameter"/>


    <concept URI="http://hi3project.com/broccoli/bsdm/profile#inputValue"
             ontology="http://hi3project.com/broccoli/bsdm#ontology">

        <property name="input" URI="http://hi3project.com/broccoli/bsdm/profile#input">
            <multiplicity min="1" max="1"/>
        </property>

    </concept>

    <concept URI="http://hi3project.com/broccoli/bsdm/profile#optional"
             ontology="http://hi3project.com/broccoli/bsdm#ontology">

        <property name="input" URI="http://hi3project.com/broccoli/bsdm/profile#input">
            <multiplicity min="0" max="*"/>
        </property>

        <property name="output" URI="http://hi3project.com/broccoli/bsdm/profile#output">
            <multiplicity min="0" max="*"/>
        </property>

        <property name="nonFunctionalProperty" URI="http://hi3project.com/broccoli/bsdm/profile#nonFunctionalProperty">
            <multiplicity min="0" max="*"/>
        </property>

    </concept>

    <concept URI="http://hi3project.com/broccoli/bsdm/profile#output"
             ontology="http://hi3project.com/broccoli/bsdm#ontology"
             subconceptOf="http://hi3project.com/broccoli/bsdm/profile#parameter"/>

    <concept URI="http://hi3project.com/broccoli/bsdm/profile#outputValue"
             ontology="http://hi3project.com/broccoli/bsdm#ontology">


        <property name="output" URI="http://hi3project.com/broccoli/bsdm/profile#output">
            <multiplicity min="1" max="1"/>
        </property>

    </concept>

    <concept URI="http://hi3project.com/broccoli/bsdm/profile#parameter"
             ontology="http://hi3project.com/broccoli/bsdm#ontology">

        <property name="name" URI="http://hi3project.com/broccoli/bsdl#literal">
            <multiplicity min="1" max="1"/>
        </property>

        <property name="type" URI="http://hi3project.com/broccoli/bsdl#semanticIdentifier">
            <multiplicity min="1" max="1"/>
        </property>

    </concept>

    <concept URI="http://hi3project.com/broccoli/bsdm/profile#parameterValue"
             ontology="http://hi3project.com/broccoli/bsdm#ontology">

        <property name="value" URI="http://hi3project.com/broccoli/bsdl#object">
            <multiplicity min="1" max="1"/>
        </property>

        <property name="type" URI="http://hi3project.com/broccoli/bsdl#uri">
            <multiplicity min="1" max="1"/>
        </property>

    </concept>

    <concept URI="http://hi3project.com/broccoli/bsdm/profile#preferred"
             ontology="http://hi3project.com/broccoli/bsdm#ontology">

        <property name="input" URI="http://hi3project.com/broccoli/bsdm/profile#input">
            <multiplicity min="0" max="*"/>
        </property>

        <property name="output" URI="http://hi3project.com/broccoli/bsdm/profile#output">
            <multiplicity min="0" max="*"/>
        </property>

        <property name="nonFunctionalProperty" URI="http://hi3project.com/broccoli/bsdm/profile#nonFunctionalProperty">
            <multiplicity min="0" max="*"/>
        </property>

    </concept>


    <concept URI="http://hi3project.com/broccoli/bsdm/profile#requestedFunctionality"
             ontology="http://hi3project.com/broccoli/bsdm#ontology"
